export const PROPERTY_TYPES = [
  'Casa',
  'Apartamento',
  'Lote/Terreno',
  'Casa em condomínio',
  'Chácara/Sítio/Fazenda',
  'Apartamento garden',
  'Cobertura',
  'JK/Loft/Studio',
  'Sobrado',
  'Flat',
  'Loft',
  'Cobertura horizontal',
];

export const AMENITIES = [
  { value: 'area-de-servico', label: 'Área de serviço' },
  { value: 'churrasqueira', label: 'Churrasqueira' },
  { value: 'piscina', label: 'Piscina' },
  { value: 'agua-quente', label: 'Água Quente' },
  { value: 'ar-condicionado', label: 'Ar-condicionado' },
  { value: 'sacada', label: 'Sacada' },
  { value: 'lavabo', label: 'Lavabo' },
  { value: 'cozinha-montada', label: 'Cozinha Montada' },
  { value: 'living', label: 'Living' },
  { value: 'lareira', label: 'Lareira' },
  { value: 'terraco', label: 'Terraço' },
  { value: 'alarme-no-imovel', label: 'Alarme' },
  { value: 'piscina-privativa', label: 'Piscina Privativa' },
  { value: 'calefacao', label: 'Calefação' },
  { value: 'sauna', label: 'Sauna' },
  { value: 'rua-silenciosa', label: 'Rua Silenciosa' },
  { value: 'ultimo-andar', label: 'Último Andar' },
  { value: 'terreo', label: 'Térreo' },
  { value: 'elevador', label: 'Elevador' },
  { value: 'gas-central', label: 'Gás Central' },
  { value: 'closet', label: 'Closet' },
];

export const NEIGHBORHOODS_FLORIANOPOLIS = [
  'Açores', 'Agronômica', 'Alto Ribeirão', 'Armação', 'Balneário',
  'Barra da Lagoa', 'Cachoeira do Bom Jesus', 'Campeche', 'Canasvieiras',
  'Carvoeira', 'Centro', 'Coqueiros', 'Costeira do Pirajubaé',
  'Daniel Lista', 'Daniela', 'Estreito', 'Ingleses', 'Itacorubi',
  'João Paulo', 'Jurerê Internacional', 'Jurerê', 'Lagoa da Conceição',
  'Morro das Pedras', 'Novo Campeche', 'Pântano do Sul', 'Pantanal',
  'Ponta das Canas', 'Porto da Lagoa', 'Ratones', 'Ribeirão da Ilha',
  'Rio Tavares', 'Sambaqui', 'Santa Mônica', 'Santo Antônio de Lisboa',
  'Santinho', 'Saco dos Limões', 'Tapera', 'Trindade', 'Vargem do Bom Jesus',
  'Vargem Grande', 'Vargem Pequena', 'Beiramar',
];

export const SORT_OPTIONS = [
  { value: 'preco_asc', label: 'Menor preço' },
  { value: 'preco_desc', label: 'Maior preço' },
  { value: 'area_desc', label: 'Maior área' },
  { value: 'area_asc', label: 'Menor área' },
  { value: 'quartos_desc', label: 'Mais quartos' },
  { value: 'recente', label: 'Mais recente' },
];

export const DEFAULT_FILTERS = {
  transacao: 'comprar',
  categoria: 'residencial',
  cidade: 'sc+florianopolis',
  bairro: [],
  quartos: '',
  tipoImovel: [],
  precoMin: '',
  precoMax: '',
  vagas: '',
  banheiros: '',
  areaMin: '',
  areaMax: '',
  mobiliado: '',
  lancamentos: '',
  exclusivo: false,
  comodidades: [],
  tags: [],
  sort: 'preco_asc',
  page: 1,
  maxPages: '',
};
